{
 "title": "variables",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "state",
    "query": {
     "query": "label_values(nginx_http_connections,state)"
    }
   },
   {
    "name": "pair",
    "query": {
     "query": "show tag values from markup with key=pair"
    }
   },
   {
    "name": "hosts",
    "query": {
     "query": "label_values(nginx_http_requests_total{host=~\".*com\"},host)"
    }
   },
   {
    "name": "statuses",
    "query": {
     "query": "label_values(nginx_http_requests_total{host=\"$hosts\"},status)"
    }
   },
   { "name": "cust", "query": "one : 1, two : 2 " },
   { "name": "consttt", "query": "89" },
   { "name": "texxt", "query": "dfgdfgdfgdfg" },
   {
    "name": "click",
    "query": "select distinct(transaction_currency) from logs.transaction_event where transaction_created_at > '2025-10-04 07:00:00'"
   }
  ]
 },
 "panels": [
  {
   "title": "no var",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{host=\"api-rot.ecommpay.com\", instance=\"lbcore.shr.2p.gate2025.nl2.etcdc.io:9145\", job=\"balancer_exporter\", status=\"404\", upstream=\"microgate\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nginx_http_requests_total_upstream{host=\"$hosts\", status=\"$statuses\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nginx_http_requests_total_upstream{status=\"$statuses\", host=\"$hosts\"} * 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{host=\"$hosts\",status=\"$statuses\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kafka_brokers{instance=\"$cust\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "markup",
     "select": [
      [
       { "params": [ "markup_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pair::tag", "operator": "=~", "value": "/^$pair$/" }
     ]
    }
   ]
  },
  {
   "title": "one panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "nginx_http_connections{state=~\"$state\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "repeat panel $state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "repeat": "state",
   "targets": [
    {
     "expr": "nginx_http_connections{state=~\"$state\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}